### ISSUE TITLE
ReferenceError: require is not defined in ES module scope in 3.0.x

### ISSUE THREAD

**Issue by edankwan** [ShaderFrog/glsl-parser#18]
```
glsl-parser/parser/parser.js:32
  } = require('./grammar');
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and ...
```

also
```
DEP0151] DeprecationWarning: No "main" or "exports" field defined in the package.json
```

**Comment by AndrewRayCode** [comment]
Wow, I think you must have installed the latest version while I was actively working on the parser. `3.0.3` is the latest version (published a few minutes later) which should have the fix.

Let me know if there's any additional issues and I can reopen. I can mark the package as deprecated in npm if that matters.
