### ISSUE TITLE
Any way of implementing location information for tokens?

### ISSUE THREAD

**Issue by Lutymane** [ShaderFrog/glsl-parser#5]
Like row and column number

**Comment by AndrewRayCode** [comment]
Yes, I have looked into it briefly but haven't made progress. It's a big TODO for the AST.

Peggyjs exposes lexeme locations using the built in `location()` function https://peggyjs.org/documentation.html#locations

I tried putting `location: location()` in the AST node constructor function: https://github.com/ShaderFrog/glsl-parser/blob/28bffb9278de0709806b147dfacc694f34f71ec8/src/parser/glsl-grammar.pegjs#L86-L89 but when I do this the tests fail with `location is not defined` - so I think there are times `node()` is called without having the right context(?) to know the location. 

Adding location to a peggyjs grammar seems like a pretty standard thing, so I'm marking this as a good first issue, in case anyone gets to it before I do.

**Comment by AndrewRayCode** [comment]
Thanks for this! A big improvement to the parser.

I updated the AST API a little bit to rename the AST key from `loc` to `location`, and I removed the `source` key from location. `source` / `grammarSource` in peggyjs is apparently the "source file name" the code came from, like 'main.js', which doesn't make sense to repeat on every AST node. I kept in the top level `grammarSource` key

**Comment by Lutymane** [comment]
Nice! I used `loc` key to have some similarity to Babel 😄 And I thought it's also more convenient due to its smaller length (easier and faster to type)
